-- migration: create flashcards table
-- purpose: store flashcards with front/back content, source tracking, and ai suggestion linking
-- affected tables: flashcards
-- special considerations:
--   - source field tracks whether flashcard was created manually or from ai
--   - accepted_from_suggestion_id links to ai_suggestions (nullable, set null on delete)
--   - cascade delete when user or deck is deleted
--   - updated_at timestamp for tracking modifications

-- create flashcards table
create table flashcards (
  id integer primary key generated by default as identity,
  user_id uuid not null references auth.users(id) on delete cascade,
  deck_id integer not null references decks(id) on delete cascade,
  front text not null,
  back text not null,
  source text not null default 'manual' check (source in ('manual', 'ai')),
  accepted_from_suggestion_id integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- create index on user_id for faster lookups by user
create index flashcards_user_id_idx on flashcards(user_id);

-- create index on deck_id for faster lookups by deck
create index flashcards_deck_id_idx on flashcards(deck_id);

-- create index on accepted_from_suggestion_id for ai suggestion tracking
create index flashcards_accepted_from_suggestion_id_idx on flashcards(accepted_from_suggestion_id);
