-- migration: create ai_suggestions table
-- purpose: store ai-generated flashcard suggestions linked to generation requests
-- affected tables: ai_suggestions
-- special considerations:
--   - linked to ai_generation_requests via generation_id (cascade delete)
--   - tracks acceptance status and conversion to actual flashcards
--   - converted_flashcard_id links to flashcards table (set null on delete)
--   - cascade delete when user is deleted

-- create ai_suggestions table
create table ai_suggestions (
  id integer primary key generated by default as identity,
  generation_id integer not null references ai_generation_requests(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  front text not null,
  back text not null,
  accepted boolean not null default false,
  accepted_at timestamptz,
  converted_flashcard_id integer references flashcards(id) on delete set null,
  created_at timestamptz not null default now()
);

-- create index on generation_id for faster lookups by generation request
create index ai_suggestions_generation_id_idx on ai_suggestions(generation_id);

-- create index on user_id for faster lookups by user
create index ai_suggestions_user_id_idx on ai_suggestions(user_id);

-- create index on accepted for filtering accepted/pending suggestions
create index ai_suggestions_accepted_idx on ai_suggestions(accepted);

-- create index on created_at for chronological queries (most recent first)
create index ai_suggestions_created_at_idx on ai_suggestions(created_at desc);
