-- migration: create flashcard_versions table
-- purpose: track version history of flashcard edits for audit trail and rollback capability
-- affected tables: flashcard_versions
-- special considerations:
--   - version_number increments for each change to a flashcard
--   - reverted_from_version_number tracks when a version is created from rollback
--   - cascade delete when flashcard is deleted
--   - changed_by user reference set to null if user deleted

-- create flashcard_versions table
create table flashcard_versions (
  id integer primary key generated by default as identity,
  flashcard_id integer not null references flashcards(id) on delete cascade,
  version_number integer not null,
  front text not null,
  back text not null,
  changed_by uuid references auth.users(id) on delete set null,
  change_reason text,
  reverted_from_version_number integer,
  created_at timestamptz not null default now(),
  constraint flashcard_versions_flashcard_version_unique unique (flashcard_id, version_number)
);

-- create index on flashcard_id for faster lookups by flashcard
create index flashcard_versions_flashcard_id_idx on flashcard_versions(flashcard_id);
