-- migration: create decks table
-- purpose: store flashcard decks owned by users
-- affected tables: decks
-- special considerations:
--   - each user can have multiple decks with unique names
--   - is_default flag allows marking one deck as default per user
--   - cascade delete when user is deleted
--   - updated_at timestamp for tracking modifications

-- create decks table
create table decks (
  id integer primary key generated by default as identity,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  description text,
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint decks_user_name_unique unique (user_id, name)
);

-- create index on user_id for faster lookups by user
create index decks_user_id_idx on decks(user_id);
