-- migration: create audit_flashcards table
-- purpose: audit trail for flashcard updates and deletions with before/after snapshots
-- affected tables: audit_flashcards
-- special considerations:
--   - captures jsonb snapshots of flashcard state before and after changes
--   - stores metadata like ip address, user agent for security auditing
--   - user_id set to null if user deleted (preserve audit trail)

-- create audit_flashcards table
create table audit_flashcards (
  id integer primary key generated by default as identity,
  flashcard_id integer not null references flashcards(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  action text not null check (action in ('update', 'delete')),
  before jsonb,
  after jsonb,
  reason text,
  source text,
  ip inet,
  user_agent text,
  created_at timestamptz not null default now()
);

-- create index on flashcard_id for faster lookups by flashcard
create index audit_flashcards_flashcard_id_idx on audit_flashcards(flashcard_id);

-- create index on user_id for faster lookups by user
create index audit_flashcards_user_id_idx on audit_flashcards(user_id);

-- create index on action for filtering by action type
create index audit_flashcards_action_idx on audit_flashcards(action);

-- create index on created_at for chronological queries (most recent first)
create index audit_flashcards_created_at_idx on audit_flashcards(created_at desc);
