-- migration: create learning_sessions table
-- purpose: track user learning sessions for spaced repetition algorithms
-- affected tables: learning_sessions
-- special considerations:
--   - algorithm field specifies which spaced repetition algorithm is used (default: sm2)
--   - deck_id is optional (null) for sessions across multiple decks
--   - ended_at remains null for ongoing sessions
--   - cascade delete when user is deleted, set null when deck is deleted

-- create learning_sessions table
create table learning_sessions (
  id integer primary key generated by default as identity,
  user_id uuid not null references auth.users(id) on delete cascade,
  deck_id integer references decks(id) on delete set null,
  algorithm text not null default 'sm2',
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  notes text
);

-- create index on user_id for faster lookups by user
create index learning_sessions_user_id_idx on learning_sessions(user_id);

-- create index on deck_id for faster lookups by deck
create index learning_sessions_deck_id_idx on learning_sessions(deck_id);

-- create index on started_at for chronological queries (most recent first)
create index learning_sessions_started_at_idx on learning_sessions(started_at desc);
