-- migration: create profiles table
-- purpose: store user profile information linked to auth.users
-- affected tables: profiles
-- special considerations:
--   - profiles.user_id references auth.users(id) with cascade delete

-- create profiles table
create table profiles (
  id integer primary key generated by default as identity,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  display_name text,
  created_at timestamptz not null default now()
);

-- create index on user_id for faster lookups
create unique index profiles_user_id_idx on profiles(user_id);
